### ISSUE TITLE
Deprecation: Resource Property Name Collision (CHEF-11)

### ISSUE THREAD

**Issue by colins** [dhoer/chef-chrome#16]
I bumped to chef-solo version 12.19.36 and this deprecation warning appeared.

Deprecated features used!
  Property `params` of resource `chrome` overwrites an existing method. Please use a different property name. This will raise an exception in Chef 13. at 1 location:
    - /var/chef/cache/cookbooks/chrome/resources/default.rb:8:in `class_from_file'
   See https://docs.chef.io/deprecations_property_name_collision.html for further details.

**Comment by dhoer** [comment]
Released v4.0.0
