### ISSUE TITLE
Cookbook is incompatible with chef client 13

### ISSUE THREAD

**Issue by kkeane** [dhoer/chef-chrome#17]
The underlying cause is the same as #16 but reporting it now because it is no longer just a warning that can be ignored. This is what happens:

ArgumentError
-------------
Property `params` of resource `chrome` overwrites an existing method.

Cookbook Trace:
---------------
  /var/cache/chef/cookbooks/chrome/resources/default.rb:8:in `class_from_file'

Relevant File Content:
----------------------
/var/cache/chef/cookbooks/chrome/resources/default.rb:

  1:  actions :master_preferences
  2:  default_action :master_preferences
  3:
  4:  attribute :name, kind_of: String, name_attribute: true
  5:  attribute :template, kind_of: String, default: 'master_preferences.json.erb'
  6:  attribute :local, kind_of: [TrueClass, FalseClass], default: false
  7:  attribute :cookbook, kind_of: String, default: nil
  8>> attribute :params, kind_of: [Array, Hash], default: []
  9:

**Comment by dhoer** [comment]
Released v4.0.0

**Comment by chinastockproducts** [comment]
we are having  same issue when upgrading to the version 13. can we know how did you resolve it.
we have same.
attribute :params, kind_of: [Array, Hash], default: []

**Comment by dhoer** [comment]
Renamed params to parameters: https://github.com/dhoer/chef-chrome/commit/6f8efe8093cd7a40262b557d40a79c2b7d95320c
