### ISSUE TITLE
Apt package google-chrome-stable=41.0.2272.101-1 randomly fails to install

### ISSUE THREAD

**Issue by dhoer** [dhoer/chef-chrome#3]
There is an issue with google-chrome-stable=41.0.2272.101-1. Installing Chrome on Ubuntu randomly fails with the following error:

```
WARNING: The following packages cannot be authenticated!
     google-chrome-stable
STDERR: E: There are problems and -y was used without --force-yes
---- End output of apt-get -q -y install google-chrome-stable=41.0.2272.101-1 
---- Ran apt-get -q -y install google-chrome-stable=41.0.2272.101-1 returned 100
```

This issue has been reported to Google.

FYI, Running the following command does NOT help:
```
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
```

**Comment by ramonskie** [comment]
the underlying problem is that the apt repo is not correctly signed
i think we can bypass this in the mean while by adding --force-yes option

```
package "google-chrome-#{node['chrome']['track']}" do
action :nothing
options "--force-yes"
end.run_action(:install)
```

**Comment by dhoer** [comment]
I don't think that is the case either, because the key outputted to the screen was correct.  I think Google has a corrupt package out on one of their CDN servers.
