### ISSUE TITLE
chrome 1.0.10 not supported chef < 12

### ISSUE THREAD

**Issue by zackyaz** [dhoer/chef-chrome#5]
Hi

i am using chef < 12 and got the following error
NoMethodError: undefined method `source_url' for #<Chef::Cookbook::Metadata:0x16c9f80>
C:/monsoon/repos/it_backend_services/litr_selenium_cp_rm_t/chef/cookbooks/chrome/metadata.rb:7:in `from_file'

thank and regards Zacky

**Comment by dhoer** [comment]
Whoops, I didn't realize source_url and issues_url were introduced in Chef 12.  I will remove those entries.
